language: python
python:
    - "3.6"
    - "3.7"
before_install:
    - pip install pip
    - pip install pytest
install:
    - pip install -r requirements.txt
    - python setup.py build_ext -i --force
script:
    pytest
