# import os
# import subprocess

import re

from setuptools import Extension, setup

# version_py = os.path.join(os.path.dirname(__file__), "_version.py")

# try:
#     version_git = subprocess.check_output(["git", "describe"]).rstrip()
# except:
#     with open(version_py, "r") as fh:
#         version_git = open(version_py).read().strip().split("=")[-1].replace('"', "")

# version_msg = "# Do not edit this file, pipeline versioning is governed by git tags"
# with open(version_py, "w") as fh:
#     fh.write(version_msg + os.linesep + "__version__=" + version_git)

VERSIONFILE = "_version.py"
verstrline = open(VERSIONFILE, "rt").read()
VSRE = r"^__version__ = ['\"]([^'\"]*)['\"]"
mo = re.search(VSRE, verstrline, re.M)
if mo:
    verstr = mo.group(1)
else:
    raise RuntimeError("Unable to find version string in %s." % (VERSIONFILE,))


def readme():
    with open("README.MD") as f:
        return f.read()


try:
    from Cython.Build import cythonize

    ext_modules = cythonize(
        [Extension(name="cython_functions", sources=["cycpd/cython/cython_functions.pyx"])]
    )

except ImportError:
    ext_modules = None

try:
    import numpy as np
except ImportError:
    raise Exception(
        "Numpy must be installed to build this pacakge.\n Install with `pip install .` or run `pip install -r requirements.txt` before building."
    )

setup(
    name="cycpd",
    version=verstr,
    description="Numpy + Cython Implementation of the Coherent Point Drift Algorithm",
    long_description=readme(),
    url="",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: MIT License",
        # 'Programming Language :: Python :: 3.4',
        # 'Programming Language :: Python :: 3.5',
        # 'Programming Language :: Python :: 3.6',
        "Topic :: Scientific/Engineering",
    ],
    keywords="image processing, point cloud, registration, mesh, surface",
    author="Anthony Gatti",
    author_email="anthony@neuralseg.com",
    license="MIT",
    ext_modules=ext_modules,
    # include_dirs=[np.get_include()],
    packages=["cycpd"],
    setup_requires=["Cython>=0.29"],
    install_requires=["numpy"],
    zip_safe=False,
)
